services:
  - type: web
    name: college-erp
    env: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      python manage.py collectstatic --no-input
      python manage.py migrate

    startCommand: "python manage.py create_admin && gunicorn --pythonpath /opt/render/project/src college_management_system.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
      - key: RENDER
        value: true
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DJANGO_SETTINGS_MODULE
        value: college_management_system.settings
      - key: DATABASE_URL
        fromDatabase:
          name: college-erp-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: .onrender.com
      - key: DEBUG
        value: false

databases:
  - name: college-erp-db
    databaseName: college_erp
    user: college_erp_user
    plan: free 